import type { Metadata } from "next";
import { Inter} from "next/font/google";
import "./globals.css";
import StarCanvas from "@/components/main/StarBackground";
import Navbar from "@/components/main/Navbar";

const interFont = Inter({
  variable: "--font-inter-font",
});

export const metadata: Metadata = {
  title: "ThreeJs Portfolio",
  description: "Generated by ThreeJs and ReactJs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interFont.variable} bg-[#030014] relative overflow-y-scroll overflow-x-hidden`}
      >
        <StarCanvas />
        <Navbar /> 
        {children}
      </body>
    </html>
  );
}
